kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-dynamic-sc
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-05b-EFS-ID
  directoryPerms: "750"
  basePath: "/efs"
  subPathPattern: "${.PVC.namespace}/${.PVC.name}"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-dynamic-sc
  resources:
    requests:
      storage: 5Gi # EFS is elastic, required by k8s

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-dynamic-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: efs-dynamic-deploy
  template:
    metadata:
      labels:
        app: efs-dynamic-deploy
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                  - efs-dynamic-deploy
            topologyKey: kubernetes.io/hostname
      volumes:
      - name: efs-volume
        persistentVolumeClaim:
          claimName: efs-dynamic-pvc
      containers:
      - name: app
        image: busybox
        command: ["sh", "-c", "sleep 3600"]
        volumeMounts:
        - name: efs-volume
          mountPath: /data
